name: catwiki
run-name: catwiki build and deploy by ${{ github.actor }}
on: push
env:
  APP_BUILD_PATH: ./app.catwiki/build
  API_BUILD_PATH: ./api.catwiki/deploy.zip

jobs:
  build-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app.catwiki
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"

      - run: npm install

      - run: npm run build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: app.catwiki
          path: ${{ env.APP_BUILD_PATH }}
          retention-days: 1

  build-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api.catwiki
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"

      - run: npm install

      - run: npm run build

      - name: Generate deployment package
        run: npm run zip

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: api.catwiki
          path: ${{ env.API_BUILD_PATH }}
          retention-days: 1


  deploy-app:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: app.catwiki
          path: app.catwiki

      - name: Deploy static site to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: projects.samhenry.tech
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-southeast-2"
          SOURCE_DIR: "./app.catwiki"
          DEST_DIR: "catwiki"

  deploy-api:
    needs: build-api
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: api.catwiki

      - name: Beanstalk Deploy for api
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: CatWiki
          environment_name: CatWiki-env
          region: ap-southeast-2
          version_label: prod-version-${{github.run_number}}
          deployment_package: deploy.zip
